
version: '2'

services:

    backend:
        image: richarvey/nginx-php-fpm:1.3.5

        restart: always
        environment:
            - PUID=1000
            - PGID=1000
        ports:
            - 79:80
        volumes:
            - ./data:/var/www/html/data
            - ./php:/var/www/html/php
            - ./errors:/var/www/errors
